version: '3.1'

services:
  app:
    image: python:3.7
    environment:
      - AWS_CONFIG_FILE=/etc/boto.cfg
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./app:/usr/src
      - ./boto.cfg:/etc/boto.cfg
    ports:
      - 8080:8080
    working_dir: /usr/src
    command: make run

  locust:
    image: python:3.7
    volumes:
      - ./locust:/usr/src
    ports:
      - 5000:5000
    working_dir: /usr/src
    command: make run
