version: '3.1'

services:
  app:
    image: python:3.7
    volumes:
      - ./app:/usr/src
      - ./boto.cfg:/etc/boto.cfg
      - pypackages:/usr/local/lib/python3.7/site-packages
    working_dir: /usr/src

volumes:
  pypackages:
    driver: local
